name: E2E Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm exec playwright install

      - name: Run E2E tests
        run: pnpm run test:e2e
        env:
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Upload Playwright Report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
