name: E2E Tests

on: push

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build application
        run: pnpm run build
      - name: Start application
        run: pnpm run start &
      - name: Wait for application to be ready
        run: npx wait-on ${{ secrets.BASE_URL }}
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm exec playwright test
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          GRAPHQL_URL: ${{ GRAPHQL_URL }}
          HYGRAPH_MUTATION_TOKEN: ${{ HYGRAPH_MUTATION_TOKEN }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
