name: Node.js CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
          cache: 'pnpm'

      - name: Install pnpm
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh -
          echo "export PNPM_HOME=\"$HOME/.local/share/pnpm\"" >> $GITHUB_ENV
          echo "export PATH=\"$PNPM_HOME:$PATH\"" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: |
          pnpm run prettier
          pnpm run lint
          pnpm run test:unit
