name: E2E Tests

on: push

jobs:
  e2e-test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build application
        run: pnpm run build
      - name: Start server
        run: pnpm run start &
      - name: Wait for server to be ready
        run: |
          echo "Waiting for server to be ready..."
          while ! nc -z localhost 3000; do
            sleep 1
          done
      - name: Install Playwright browsers
        run: pnpm exec playwright install
      - name: Run E2E tests
        run: pnpm run test:e2e
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
      - name: Upload Playwright Report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
